[package]
name = "cosmwasm-bignumber"
version = "2.2.0-rc3"
authors = ["Terraform Labs, PTE."]
edition = "2018"
description = "Bignumber library for cosmwasm project"
license = "Apache-2.0"
repository = "https://github.com/terra-project/terra-cosmwasm"
homepage = "https://terra.money"
documentation = "https://docs.terra.money"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = "0.16.0-rc5"
bigint = "4"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

[dev-dependencies]
cosmwasm-schema = "0.16.0-rc5"
